"use client";
import Loader from '@/components/Loader';
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { useEffect, useState } from 'react'
import { ToastContainer } from 'react-toastify'
import { Provider } from 'react-redux';
import store from '@/redux/store';
import 'devextreme/dist/css/dx.light.css';
const inter = Inter({ subsets: ['latin'] })

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {


  // const [loading, setLoading] = useState<boolean>(true);
  const [loading, setLoading] = useState<boolean>(false);

  useEffect(() => {
    // setTimeout(() => setLoading(false), 1000);
  }, []);

  return (
    <html lang="en">
      <body className={`${inter.className} demo-container`} id="root" >
        <div className="dark:bg-boxdark-2 dark:text-bodydark min-h-screen">
          {loading ?
            <>
              <Loader />
            </> :
            <>
              <Provider store={store}>
                <ToastContainer />
                {children}
              </Provider>
            </>
          }
        </div>
      </body>
    </html>
  )
}
