"use client";
import Loader from '@/components/Loader';
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { useEffect, useState } from 'react'
import { ToastContainer } from 'react-toastify'
import { Provider } from 'react-redux';
import store from '@/redux/store';
import 'devextreme/dist/css/dx.light.css';
import { LocalizationProvider } from '@mui/x-date-pickers';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs'
import createCache from '@emotion/cache';
import { CacheProvider } from '@emotion/react';
import { createTheme, ThemeProvider } from '@mui/material/styles';
import rtlPlugin from 'stylis-plugin-rtl';
import { prefixer } from 'stylis';


const inter = Inter({ subsets: ['latin'] })

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {


  // const [loading, setLoading] = useState<boolean>(true);
  const [loading, setLoading] = useState<boolean>(false);

  useEffect(() => {
    // setTimeout(() => setLoading(false), 1000);
  }, []);

  const theme = createTheme({
    direction: 'rtl', // Both here and <body dir="rtl">
  });
  // Create rtl cache
  const cacheRtl = createCache({
    key: 'muirtl',
    stylisPlugins: [prefixer, rtlPlugin],
  });

  return (
    <html lang="en">
      <body className={`${inter.className} demo-container`} id="root" >
        <div className="dark:bg-boxdark-2 dark:text-bodydark min-h-screen">
          {loading ?
            <>
              <Loader />
            </> :
            <>
              <Provider store={store}>
                <CacheProvider value={cacheRtl}>
                  <ThemeProvider theme={theme}>
                    <LocalizationProvider dateAdapter={AdapterDayjs}>
                      <ToastContainer />
                      {children}
                    </LocalizationProvider>
                  </ThemeProvider>
                </CacheProvider>
              </Provider>
            </>
          }
        </div>
      </body>
    </html>
  )
}
